#!/bin/sh

set -e -x

# ===================================================
# Kernel Tree and Toolchain Setup
# ===================================================
KERNEL_SOURCE="https://github.com/rdbckp/a022f_kernel"
KERNEL_BRANCH="master"
KERNEL_DEFCONFIG="a02_defconfig"
# Prebuilt Clang Toolchain
CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12L-s1-release/clang-r416183b1.tar.gz"
# Prebuilt GCC Utilities
GCC_URL="https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git"
GCC_BRANCH="lineage-19.1"

# ===================================================
# Cloning and Downloading
# ===================================================
if [ ! -d clang ]; then mkdir clang && curl -Lsq "${CLANG_URL}" -o clang.tgz && tar -xzf clang.tgz -C clang; fi
# if [ ! -d gcc ]; then mkdir gcc && curl -Lsq "${GCC_URL}" -o gcc.tgz && tar -xzf gcc.tgz -C gcc; fi
# if [ ! -d gcc ]; then mkdir gcc && curl -Lsq "${GCC_URL}" -o gcc.tar.xz && unxz gcc.tar.xz && tar -xvf gcc.tar -C gcc; fi
# [ ! -d clang ] && git clone --depth=1 "${CLANG_URL}" -b "${CLANG_BRANCH}" ./clang
[ ! -d gcc ] && git clone --depth=1 "${GCC_URL}" -b "${GCC_BRANCH}" ./gcc
[ ! -d "${KERNEL}" ] && git clone --depth=1 "${KERNEL_SOURCE}" -b "${KERNEL_BRANCH}" "${KERNEL}"

# ===================================================
# Make Command Setup
# ===================================================
xxx() {
	ARCH=arm CC=clang HOSTCC=clang \
	CLANG_TRIPLE=arm-linux-gnueabi- CXX=clang++ \
	CROSS_COMPILE=arm-linux-androideabi- \
	KCFLAGS=-w CFLAGS_WARN=-Wunused-but-set-variable \
	CONFIG_SECTION_MISMATCH_WARN_ONLY=y "$@"
}

# ===================================================
# Folder and Path Setup
# ===================================================
WORK="${HOME}/work"
KERNEL="myKernel"
KERNEL_SRC="${WORK}/${KERNEL}"
mkdir -p "${WORK}"
cd "${WORK}" || exit 1
PATH="${WORK}/clang/bin:${WORK}/gcc/bin:/bin"

# ===================================================
# Compiling
# ===================================================
cd "${KERNEL_SRC}" || exit 1
make ${xxx} clean && make ${xxx} mrproper
make O=out ${xxx} "${KERNEL_DEFCONFIG}"
make O=out ${xxx} -j"$(nproc --all)" 2>&1 | tee build.log 
