#!/bin/sh

set -e -x

# Kernel Source
KERNEL_SOURCE="https://github.com/rdbckp/linux"
KERNEL_BRANCH="main"

KERNEL_DEFCONFIG="a02_defconfig"

# Setup Folder
WORK="${HOME}/work"
KERNEL="myKernel"
KERNEL_SRC="${WORK}/${KERNEL}"
mkdir -p "${WORK}"
cd "${WORK}"

# Cloning kernel
[ ! -d "${KERNEL}" ] && git clone --depth=1 "${KERNEL_SOURCE}" -b "${KERNEL_BRANCH}" "${KERNEL}"
