#!/bin/sh

set -e -x

# Kernel Source
KERNEL_SOURCE="https://github.com/physwizz/a022f-u2"
KERNEL_BRANCH="main"

# Setup Folder
WORK="/home/runner/work/kernel_builder/kernel_builder/work"
KERNEL="myKernel"
KERNEL_SRC="${WORK}/${KERNEL}"
mkdir -p "${WORK}"
cd "${WORK}"

# Cloning kernel
cd $WORK
[ ! -d "${KERNEL}" ] && git clone --depth=1 "${KERNEL_SOURCE}" -b "${KERNEL_BRANCH}" "${KERNEL}"
